;
; keyboard values for special keys
;
 
; Backspace key 
KEY_BACKSPACE = 8
; Enter key 
KEY_ENTER = 10
; Escape key
KEY_ESC = 27
; Insert key
KEY_INSERT = 128
; Delete key
KEY_DELETE = 129
; Home key
KEY_HOME = 130
; End key
KEY_END = 131
; PageUp key
KEY_PAGE_UP = 132
; PageDown key
KEY_PAGE_DOWN = 133
; CursorUp key
KEY_CURSOR_UP = 134
; CursorDown key
KEY_CURSOR_DOWN = 135
; CursorLeft key
KEY_CURSOR_LEFT = 136
; CursorRight key
KEY_CURSOR_RIGHT = 137
