;
; List of all assembler tokens
;
opcode_tokens:
OPC_ADD = 0x01
    #d "add"
OPC_AND = 0x02
    #d "and"
OPC_CII = 0x03
    #d "cii"
OPC_CLC = 0x04
    #d "clc"
OPC_CMP = 0x05
    #d "cmp"
OPC_DCC = 0x06
    #d "dcc"
OPC_DEC = 0x07
    #d "dec"
OPC_HLT = 0x08
    #d "hlt"
OPC_ICC = 0x09
    #d "icc"
OPC_INB = 0x0a
    #d "inb"
OPC_INC = 0x0b
    #d "inc"
OPC_INP = 0x0c
    #d "inp"
OPC_INW = 0x0d
    #d "inw"
OPC_JCS = 0x0e
    #d "jcs"
OPC_JMP = 0x0f
    #d "jmp"
OPC_JNC = 0x10
    #d "jnc"
OPC_JNN = 0x11
    #d "jnn"
OPC_JNS = 0x12
    #d "jns"
OPC_JNV = 0x13
    #d "jnv"
OPC_JNZ = 0x14
    #d "jnz"
OPC_JSR = 0x15
    #d "jsr"
OPC_JVS = 0x16
    #d "jvs"
OPC_JZS = 0x17
    #d "jzs"
OPC_LSL = 0x18
    #d "lsl"
OPC_LSR = 0x19
    #d "lsr"
OPC_MOV = 0x1a
    #d "mov"
OPC_MVA = 0x1b
    #d "mva"
OPC_NOP = 0x1c
    #d "nop"
OPC_OR = 0x1d
    #d "or "
OPC_OUB = 0x1e
    #d "oub"
OPC_OUT = 0x1f
    #d "out"
OPC_OUW = 0x20
    #d "ouw"
OPC_PLB = 0x21
    #d "plb"
OPC_PLF = 0x22
    #d "plf"
OPC_PSB = 0x23
    #d "psb"
OPC_PSF = 0x24
    #d "psf"
OPC_PSH = 0x25
    #d "psh"
OPC_PUL = 0x26
    #d "pul"
OPC_RTI = 0x27
    #d "rti"
OPC_RTS = 0x28
    #d "rts"
OPC_SII = 0x29
    #d "sii"
OPC_STC = 0x2a
    #d "stc"
OPC_STR = 0x2b
    #d "str"
OPC_STW = 0x2c
    #d "stw"
OPC_SUB = 0x2d
    #d "sub"
OPC_XOR = 0x2e
    #d "xor"
opcode_tokens_end:
